apiVersion: v1
kind: Service
metadata:
  name: test-api
  labels:
    app: test-api
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: test-api
  type: LoadBalancer
  selector:
    app: test-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  labels:
    app: test-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - name: test-api
          image: grc.io/practise-project-254301/test-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
